### ISSUE TITLE
ObservationMannerOfDeath - Certifier Not Added to Resource Dictionary

### ISSUE THREAD

**Issue by reece-berens** [mmg-fhir-ig/cbs-ig-dotnet#10]
When setting the Certifier property on an ObservationMannerOfDeath object, the code doesn't add the Practitioner to the resources dictionary, meaning I can't get the Practitioner item through the resources dictionary if needed. It should work similar to the SubjectAsResource setter on that object.

**Comment by myungchoi** [comment]
Practitioner resource is added to the resources dictionary.
