### ISSUE TITLE
Incorrect Value Set URL

### ISSUE THREAD

**Issue by reece-berens** [mmg-fhir-ig/cbs-ig-dotnet#7]
The MdiVsDateEstablishmentApproach value set class in GaTech.Chai.Mdi/Common
/MdiCodeSystemsValueSets.cs has the URL for the Place of Death value set. The URL should be http://hl7.org/fhir/us/mdi/ValueSet/ValueSet-date-establishment-approach instead. 

There are a few of the classes that don't have an official URL field in them, not sure if that's something that would be needed in each class.

**Comment by myungchoi** [comment]
Error fixed. And, missing official URLs are added. A class that was not referenced is deleted.
