### ISSUE TITLE
Extra Whitespace in Some Codes

### ISSUE THREAD

**Issue by reece-berens** [mmg-fhir-ig/cbs-ig-dotnet#8]
Some of the codes in GaTech.Chai.Mdi/Common/MdiCodeSystemsValueSets.cs have extra whitespace in them, which cause issues when attempting to compare values in a JSON bundle to the static instances of the codes in this file.

Codes with extra whitespace:
- MdiCodeSystem.LocalComponentCodes => SecondOtherPacificIslanderCode 
- MdiCodeSystem.LocalComponentCodes => HispanicCode 
- MdiCodeSystem.LocalComponentCodes => RACEMVR
- MdiCodeSystem.LocalComponentCodes => HispanicPuertoRican
- MdiCodeSystem.LocalComponentCodes => HispanicOther
- MdiCodeSystem.LocalComponentCodes => White
- MdiCodeSystem.LocalComponentCodes => AmericanIndianOrAlaskanNative
- MdiCodeSystem.DeathPregnancyStatus => NA
- MdiVsMannerOfDeath => DeathmannerUndetermined
- MdiVsContributoryTobaccoUse => No
- MdiVsCertifierTypes => PronouncingAndCertifyingPhysican

**Comment by myungchoi** [comment]
extra spaces removed.
