### ISSUE TITLE
Namespace Issues

### ISSUE THREAD

**Issue by reece-berens** [mmg-fhir-ig/cbs-ig-dotnet#9]
Some areas of the MDI portion of the code have incorrect namespaces, which mean that I need to include two different namespaces for a single component.

These are the areas I found that have different namespaces:
- ObservationContributingCauseOfDeathPart2 - main file has ObservationContributingCauseOfDeathPart2Profile, extension file has ObservationConditionContributingToDeathProfile
- ProcedureDeathCertificationProfile - main file has ProceDureDeathCertificationProfile (notice uppercase D in Procedure), extension file has ProcedureDeathCertificationProfile
- ObservationAutopsyPerformedIndicatorProfile - the extension file has the class name ObservationDecedentPregnancyExtensions

**Comment by myungchoi** [comment]
Corrected.
